//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerHardwareStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.OrderBuy = new HashSet<OrderBuy>();
        }
    
        public int ID_Invoice { get; set; }
        public System.DateTime DateInvoice { get; set; }
        public int ID_UserBuyer { get; set; }
        public int ID_OrderStatus { get; set; }
        public int ID_Personnel { get; set; }
        public decimal TotalSumm { get; set; }
        public string DeliveryAddress { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual UserBuyer UserBuyer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBuy> OrderBuy { get; set; }
    }
}
